### ISSUE TITLE
there is no aihelp binary generated to use aihelp

### ISSUE THREAD

**Issue by zenitogr** [mihir-s-05/aihelp#3]
after running the commands in the instructions:
```
aihelp> tree
Folder PATH listing
Volume serial number is E6DB-1ACC
C:.
├───.git
│   ├───branches
│   ├───hooks
│   ├───info
│   ├───logs
│   │   └───refs
│   │       ├───heads
│   │       └───remotes
│   │           └───origin
│   ├───objects
│   │   ├───info
│   │   └───pack
│   └───refs
│       ├───heads
│       ├───remotes
│       │   └───origin
│       └───tags
├───.venv
│   ├───Lib
│   │   └───site-packages
│   │       └───__pycache__
│   └───Scripts
├───aihelp
└───aihelp.egg-info
```
aihelp here is a empty folder

**Comment by mihir-s-05** [comment]
Try running the commands with the updated instructions, let me know if that helps after resetting the directory

**Comment by zenitogr** [comment]
~~still no binary available~~ ok binary available but I get an error no module named aihelp
```
aihelp
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\all\AI\aihelp\test1\aihelp\aihelp\venv\Scripts\aihelp.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'aihelp'
(venv) PS C:\all\AI\aihelp\test1\aihelp\aihelp> ls


    Directory: C:\all\AI\aihelp\test1\aihelp\aihelp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          1/8/2024  10:24 πμ                .git
d-----          1/8/2024  10:24 πμ                aihelp
d-----          1/8/2024  10:25 πμ                aihelp.egg-info
d-----          1/8/2024  10:24 πμ                venv
-a----          1/8/2024   9:06 πμ             69 .env
-a----          1/8/2024  10:24 πμ            261 .gitignore
-a----          1/8/2024  10:24 πμ           2341 README.md
-a----          1/8/2024  10:24 πμ             32 requirements.txt
-a----          1/8/2024  10:24 πμ            812 setup.py
```
here is the output of running the install command:
```
pip install -e .
Obtaining file:///C:/all/AI/aihelp/test1/aihelp/aihelp
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: groq in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from aihelp==0.1) (0.9.0)
Requirement already satisfied: python-dotenv in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from aihelp==0.1) (1.0.1)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from groq->aihelp==0.1) (4.4.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from groq->aihelp==0.1) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from groq->aihelp==0.1) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from groq->aihelp==0.1) (2.8.2)
Requirement already satisfied: sniffio in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from groq->aihelp==0.1) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.7 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from groq->aihelp==0.1) (4.12.2)
Requirement already satisfied: idna>=2.8 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from anyio<5,>=3.5.0->groq->aihelp==0.1) (3.7)
Requirement already satisfied: certifi in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from httpx<1,>=0.23.0->groq->aihelp==0.1) (2024.7.4)
Requirement already satisfied: httpcore==1.* in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from httpx<1,>=0.23.0->groq->aihelp==0.1) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq->aihelp==0.1) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from pydantic<3,>=1.9.0->groq->aihelp==0.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\all\ai\aihelp\test1\aihelp\aihelp\venv\lib\site-packages (from pydantic<3,>=1.9.0->groq->aihelp==0.1) (2.20.1)
Building wheels for collected packages: aihelp
  Building editable for aihelp (pyproject.toml) ... done
  Created wheel for aihelp: filename=aihelp-0.1-0.editable-py3-none-any.whl size=3911 sha256=6538e2b3a46613a549378125ec678d6dc689a8723937bee0f4ab3008d2f35b95
  Stored in directory: C:\Users\zengo\AppData\Local\Temp\pip-ephem-wheel-cache-gofvqani\wheels\4c\86\b8\ef5f1526ea18b823db821d691f1863ab10952d84680caa33e2
Successfully built aihelp
Installing collected packages: aihelp
Successfully installed aihelp-0.1
```

**Comment by mihir-s-05** [comment]
Something that worked for me when installing on a different machine was running `pip install -e .` Try that maybe. I haven't really been able to test on Windows yet unfortunately.
